window.dataset = 
[
  {
    "Team": "Belgium",
    "#": 21,
    "Pos.": "FW",
    "FIFA Popular Name": "BATSHUAYI Michy",
    "Birth Date": "02.10.1993",
    "Shirt Name": "BATSHUAYI",
    "Club": "Borussia Dortmund (GER)",
    "Height": 185,
    "Weight": 78
  },
  {
    "Team": "Germany",
    "#": 11,
    "Pos.": "FW",
    "FIFA Popular Name": "REUS Marco",
    "Birth Date": "31.05.1989",
    "Shirt Name": "REUS",
    "Club": "Borussia Dortmund (GER)",
    "Height": 180,
    "Weight": 67
  },
  {
    "Team": "Japan",
    "#": 10,
    "Pos.": "MF",
    "FIFA Popular Name": "KAGAWA Shinji",
    "Birth Date": "17.03.1989",
    "Shirt Name": "KAGAWA",
    "Club": "Borussia Dortmund (GER)",
    "Height": 175,
    "Weight": 68
  },
  {
    "Team": "Poland",
    "#": 20,
    "Pos.": "DF",
    "FIFA Popular Name": "PISZCZEK Lukasz",
    "Birth Date": "03.06.1985",
    "Shirt Name": "PISZCZEK",
    "Club": "Borussia Dortmund (GER)",
    "Height": 184,
    "Weight": 79
  },
  {
    "Team": "Portugal",
    "#": 5,
    "Pos.": "DF",
    "FIFA Popular Name": "RAPHAEL GUERREIRO",
    "Birth Date": "22.12.1993",
    "Shirt Name": "RAPHAEL",
    "Club": "Borussia Dortmund (GER)",
    "Height": 170,
    "Weight": 64
  },
  {
    "Team": "Switzerland",
    "#": 21,
    "Pos.": "GK",
    "FIFA Popular Name": "BUERKI Roman",
    "Birth Date": "14.11.1990",
    "Shirt Name": "BÜRKI",
    "Club": "Borussia Dortmund (GER)",
    "Height": 188,
    "Weight": 83
  },
  {
    "Team": "Switzerland",
    "#": 5,
    "Pos.": "DF",
    "FIFA Popular Name": "AKANJI Manuel",
    "Birth Date": "19.07.1995",
    "Shirt Name": "AKANJI",
    "Club": "Borussia Dortmund (GER)",
    "Height": 186,
    "Weight": 85
  },
  {
    "Team": "Argentina",
    "#": 23,
    "Pos.": "GK",
    "FIFA Popular Name": "CABALLERO Wilfredo",
    "Birth Date": "28.09.1981",
    "Shirt Name": "CABALLERO",
    "Club": "Chelsea FC (ENG)",
    "Height": 186,
    "Weight": 80
  },
  {
    "Team": "Belgium",
    "#": 10,
    "Pos.": "FW",
    "FIFA Popular Name": "HAZARD Eden",
    "Birth Date": "07.01.1991",
    "Shirt Name": "E. HAZARD",
    "Club": "Chelsea FC (ENG)",
    "Height": 173,
    "Weight": 74
  },
  {
    "Team": "Belgium",
    "#": 1,
    "Pos.": "GK",
    "FIFA Popular Name": "COURTOIS Thibaut",
    "Birth Date": "11.05.1992",
    "Shirt Name": "COURTOIS",
    "Club": "Chelsea FC (ENG)",
    "Height": 199,
    "Weight": 91
  },
  {
    "Team": "Brazil",
    "#": 19,
    "Pos.": "MF",
    "FIFA Popular Name": "WILLIAN",
    "Birth Date": "09.08.1988",
    "Shirt Name": "WILLIAN",
    "Club": "Chelsea FC (ENG)",
    "Height": 175,
    "Weight": 77
  },
  {
    "Team": "Denmark",
    "#": 6,
    "Pos.": "DF",
    "FIFA Popular Name": "CHRISTENSEN Andreas",
    "Birth Date": "10.04.1996",
    "Shirt Name": "CHRISTENSEN",
    "Club": "Chelsea FC (ENG)",
    "Height": 192,
    "Weight": 85
  },
  {
    "Team": "England",
    "#": 21,
    "Pos.": "MF",
    "FIFA Popular Name": "LOFTUS-CHEEK Ruben",
    "Birth Date": "23.01.1996",
    "Shirt Name": "LOFTUS-CHEEK",
    "Club": "Chelsea FC (ENG)",
    "Height": 190,
    "Weight": 73
  },
  {
    "Team": "England",
    "#": 15,
    "Pos.": "DF",
    "FIFA Popular Name": "CAHILL Gary",
    "Birth Date": "19.12.1985",
    "Shirt Name": "CAHILL",
    "Club": "Chelsea FC (ENG)",
    "Height": 191,
    "Weight": 85
  },
  {
    "Team": "France",
    "#": 13,
    "Pos.": "MF",
    "FIFA Popular Name": "KANTE Ngolo",
    "Birth Date": "29.03.1991",
    "Shirt Name": "KANTE",
    "Club": "Chelsea FC (ENG)",
    "Height": 168,
    "Weight": 70
  },
  {
    "Team": "France",
    "#": 9,
    "Pos.": "FW",
    "FIFA Popular Name": "GIROUD Olivier",
    "Birth Date": "30.09.1986",
    "Shirt Name": "GIROUD",
    "Club": "Chelsea FC (ENG)",
    "Height": 193,
    "Weight": 91
  },
  {
    "Team": "Germany",
    "#": 16,
    "Pos.": "DF",
    "FIFA Popular Name": "RUEDIGER Antonio",
    "Birth Date": "03.03.1993",
    "Shirt Name": "RÜDIGER",
    "Club": "Chelsea FC (ENG)",
    "Height": 191,
    "Weight": 85
  },
  {
    "Team": "Nigeria",
    "#": 11,
    "Pos.": "FW",
    "FIFA Popular Name": "MOSES Victor",
    "Birth Date": "12.12.1990",
    "Shirt Name": "MOSES",
    "Club": "Chelsea FC (ENG)",
    "Height": 177,
    "Weight": 75
  },
  {
    "Team": "Spain",
    "#": 14,
    "Pos.": "DF",
    "FIFA Popular Name": "AZPILICUETA Cesar",
    "Birth Date": "28.08.1989",
    "Shirt Name": "AZPILICUETA",
    "Club": "Chelsea FC (ENG)",
    "Height": 178,
    "Weight": 78
  },
  {
    "Team": "Colombia",
    "#": 1,
    "Pos.": "GK",
    "FIFA Popular Name": "OSPINA David",
    "Birth Date": "31.08.1988",
    "Shirt Name": "OSPINA",
    "Club": "Arsenal FC (ENG)",
    "Height": 183,
    "Weight": 80
  },
  {
    "Team": "Egypt",
    "#": 17,
    "Pos.": "MF",
    "FIFA Popular Name": "MOHAMED ELNENY",
    "Birth Date": "11.07.1992",
    "Shirt Name": "M. ELNENY",
    "Club": "Arsenal FC (ENG)",
    "Height": 181,
    "Weight": 74
  },
  {
    "Team": "England",
    "#": 14,
    "Pos.": "FW",
    "FIFA Popular Name": "WELBECK Danny",
    "Birth Date": "26.11.1990",
    "Shirt Name": "WELBECK",
    "Club": "Arsenal FC (ENG)",
    "Height": 184,
    "Weight": 78
  },
  {
    "Team": "Germany",
    "#": 10,
    "Pos.": "MF",
    "FIFA Popular Name": "OEZIL Mesut",
    "Birth Date": "15.10.1988",
    "Shirt Name": "ÖZIL",
    "Club": "Arsenal FC (ENG)",
    "Height": 180,
    "Weight": 70
  },
  {
    "Team": "Nigeria",
    "#": 18,
    "Pos.": "FW",
    "FIFA Popular Name": "IWOBI Alex",
    "Birth Date": "03.05.1996",
    "Shirt Name": "IWOBI",
    "Club": "Arsenal FC (ENG)",
    "Height": 185,
    "Weight": 86
  },
  {
    "Team": "Spain",
    "#": 16,
    "Pos.": "DF",
    "FIFA Popular Name": "MONREAL Nacho",
    "Birth Date": "26.02.1986",
    "Shirt Name": "MONREAL",
    "Club": "Arsenal FC (ENG)",
    "Height": 179,
    "Weight": 72
  },
  {
    "Team": "Switzerland",
    "#": 10,
    "Pos.": "MF",
    "FIFA Popular Name": "XHAKA Granit",
    "Birth Date": "27.09.1992",
    "Shirt Name": "XHAKA",
    "Club": "Arsenal FC (ENG)",
    "Height": 183,
    "Weight": 82
  },
  {
    "Team": "Belgium",
    "#": 17,
    "Pos.": "MF",
    "FIFA Popular Name": "TIELEMANS Youri",
    "Birth Date": "07.05.1997",
    "Shirt Name": "TIELEMANS",
    "Club": "AS Monaco (FRA)",
    "Height": 176,
    "Weight": 72
  },
  {
    "Team": "Colombia",
    "#": 9,
    "Pos.": "FW",
    "FIFA Popular Name": "FALCAO Radamel",
    "Birth Date": "10.02.1986",
    "Shirt Name": "FALCAO",
    "Club": "AS Monaco (FRA)",
    "Height": 177,
    "Weight": 72
  },
  {
    "Team": "Croatia",
    "#": 23,
    "Pos.": "GK",
    "FIFA Popular Name": "SUBASIC Danijel",
    "Birth Date": "27.10.1984",
    "Shirt Name": "SUBAŠIĆ",
    "Club": "AS Monaco (FRA)",
    "Height": 191,
    "Weight": 84
  },
  {
    "Team": "France",
    "#": 8,
    "Pos.": "FW",
    "FIFA Popular Name": "LEMAR Thomas",
    "Birth Date": "12.11.1995",
    "Shirt Name": "LEMAR",
    "Club": "AS Monaco (FRA)",
    "Height": 172,
    "Weight": 65
  },
  {
    "Team": "France",
    "#": 19,
    "Pos.": "DF",
    "FIFA Popular Name": "SIDIBE Djibril",
    "Birth Date": "29.07.1992",
    "Shirt Name": "SIDIBE",
    "Club": "AS Monaco (FRA)",
    "Height": 184,
    "Weight": 81
  },
  {
    "Team": "Poland",
    "#": 15,
    "Pos.": "DF",
    "FIFA Popular Name": "GLIK Kamil",
    "Birth Date": "03.02.1988",
    "Shirt Name": "GLIK",
    "Club": "AS Monaco (FRA)",
    "Height": 190,
    "Weight": 80
  },
  {
    "Team": "Portugal",
    "#": 8,
    "Pos.": "MF",
    "FIFA Popular Name": "JOAO MOUTINHO",
    "Birth Date": "08.09.1986",
    "Shirt Name": "J. MOUTINHO",
    "Club": "AS Monaco (FRA)",
    "Height": 170,
    "Weight": 61
  },
  {
    "Team": "Senegal",
    "#": 20,
    "Pos.": "FW",
    "FIFA Popular Name": "BALDE Keita",
    "Birth Date": "08.03.1995",
    "Shirt Name": "KEÏTA BALDE",
    "Club": "AS Monaco (FRA)",
    "Height": 181,
    "Weight": 77
  },
  {
    "Team": "Brazil",
    "#": 6,
    "Pos.": "DF",
    "FIFA Popular Name": "FILIPE LUIS",
    "Birth Date": "09.08.1985",
    "Shirt Name": "FILIPE LUIS",
    "Club": "Atletico Madrid (ESP)",
    "Height": 182,
    "Weight": 73
  },
  {
    "Team": "Croatia",
    "#": 2,
    "Pos.": "DF",
    "FIFA Popular Name": "VRSALJKO Sime",
    "Birth Date": "10.01.1992",
    "Shirt Name": "VRSALJKO",
    "Club": "Atletico Madrid (ESP)",
    "Height": 181,
    "Weight": 76
  },
  {
    "Team": "France",
    "#": 7,
    "Pos.": "FW",
    "FIFA Popular Name": "GRIEZMANN Antoine",
    "Birth Date": "21.03.1991",
    "Shirt Name": "GRIEZMANN",
    "Club": "Atletico Madrid (ESP)",
    "Height": 174,
    "Weight": 72
  },
  {
    "Team": "France",
    "#": 21,
    "Pos.": "DF",
    "FIFA Popular Name": "HERNANDEZ Lucas",
    "Birth Date": "14.02.1996",
    "Shirt Name": "HERNANDEZ",
    "Club": "Atletico Madrid (ESP)",
    "Height": 183,
    "Weight": 76
  },
  {
    "Team": "Spain",
    "#": 8,
    "Pos.": "MF",
    "FIFA Popular Name": "KOKE",
    "Birth Date": "08.01.1992",
    "Shirt Name": "KOKE",
    "Club": "Atletico Madrid (ESP)",
    "Height": 176,
    "Weight": 73
  },
  {
    "Team": "Spain",
    "#": 7,
    "Pos.": "MF",
    "FIFA Popular Name": "SAUL",
    "Birth Date": "21.11.1994",
    "Shirt Name": "SAÚL",
    "Club": "Atletico Madrid (ESP)",
    "Height": 183,
    "Weight": 76
  },
  {
    "Team": "Spain",
    "#": 19,
    "Pos.": "FW",
    "FIFA Popular Name": "COSTA Diego",
    "Birth Date": "07.10.1988",
    "Shirt Name": "DIEGO COSTA",
    "Club": "Atletico Madrid (ESP)",
    "Height": 185,
    "Weight": 86
  },
  {
    "Team": "Uruguay",
    "#": 3,
    "Pos.": "DF",
    "FIFA Popular Name": "GODIN Diego",
    "Birth Date": "16.02.1986",
    "Shirt Name": "GODIN",
    "Club": "Atletico Madrid (ESP)",
    "Height": 185,
    "Weight": 73
  },
  {
    "Team": "Uruguay",
    "#": 2,
    "Pos.": "DF",
    "FIFA Popular Name": "GIMENEZ Jose",
    "Birth Date": "20.01.1995",
    "Shirt Name": "J.M. GIMENEZ",
    "Club": "Atletico Madrid (ESP)",
    "Height": 185,
    "Weight": 77
  },
  {
    "Team": "Argentina",
    "#": 10,
    "Pos.": "FW",
    "FIFA Popular Name": "MESSI Lionel",
    "Birth Date": "24.06.1987",
    "Shirt Name": "MESSI",
    "Club": "FC Barcelona (ESP)",
    "Height": 170,
    "Weight": 72
  },
  {
    "Team": "Belgium",
    "#": 3,
    "Pos.": "DF",
    "FIFA Popular Name": "VERMAELEN Thomas",
    "Birth Date": "14.11.1985",
    "Shirt Name": "VERMAELEN",
    "Club": "FC Barcelona (ESP)",
    "Height": 183,
    "Weight": 80
  },
  {
    "Team": "Brazil",
    "#": 11,
    "Pos.": "MF",
    "FIFA Popular Name": "PHILIPPE COUTINHO",
    "Birth Date": "12.06.1992",
    "Shirt Name": "P. COUTINHO",
    "Club": "FC Barcelona (ESP)",
    "Height": 172,
    "Weight": 68
  },
  {
    "Team": "Brazil",
    "#": 15,
    "Pos.": "MF",
    "FIFA Popular Name": "PAULINHO",
    "Birth Date": "25.07.1988",
    "Shirt Name": "PAULINHO",
    "Club": "FC Barcelona (ESP)",
    "Height": 181,
    "Weight": 81
  },
  {
    "Team": "Colombia",
    "#": 13,
    "Pos.": "DF",
    "FIFA Popular Name": "MINA Yerry",
    "Birth Date": "23.09.1994",
    "Shirt Name": "Y. MINA",
    "Club": "FC Barcelona (ESP)",
    "Height": 194,
    "Weight": 95
  },
  {
    "Team": "Croatia",
    "#": 7,
    "Pos.": "MF",
    "FIFA Popular Name": "RAKITIC Ivan",
    "Birth Date": "10.03.1988",
    "Shirt Name": "RAKITIĆ",
    "Club": "FC Barcelona (ESP)",
    "Height": 184,
    "Weight": 78
  },
  {
    "Team": "France",
    "#": 11,
    "Pos.": "FW",
    "FIFA Popular Name": "DEMBELE Ousmane",
    "Birth Date": "15.05.1997",
    "Shirt Name": "DEMBELE",
    "Club": "FC Barcelona (ESP)",
    "Height": 178,
    "Weight": 70
  },
  {
    "Team": "France",
    "#": 5,
    "Pos.": "DF",
    "FIFA Popular Name": "UMTITI Samuel",
    "Birth Date": "14.11.1993",
    "Shirt Name": "UMTITI",
    "Club": "FC Barcelona (ESP)",
    "Height": 183,
    "Weight": 84
  },
  {
    "Team": "Germany",
    "#": 22,
    "Pos.": "GK",
    "FIFA Popular Name": "TER STEGEN Marc-Andre",
    "Birth Date": "30.04.1992",
    "Shirt Name": "TER STEGEN",
    "Club": "FC Barcelona (ESP)",
    "Height": 187,
    "Weight": 85
  },
  {
    "Team": "Spain",
    "#": 6,
    "Pos.": "MF",
    "FIFA Popular Name": "INIESTA Andres",
    "Birth Date": "11.05.1984",
    "Shirt Name": "A. INIESTA",
    "Club": "FC Barcelona (ESP)",
    "Height": 171,
    "Weight": 68
  },
  {
    "Team": "Spain",
    "#": 18,
    "Pos.": "DF",
    "FIFA Popular Name": "ALBA Jordi",
    "Birth Date": "21.03.1989",
    "Shirt Name": "JORDI ALBA",
    "Club": "FC Barcelona (ESP)",
    "Height": 170,
    "Weight": 68
  },
  {
    "Team": "Spain",
    "#": 5,
    "Pos.": "MF",
    "FIFA Popular Name": "BUSQUETS Sergio",
    "Birth Date": "16.07.1988",
    "Shirt Name": "SERGIO",
    "Club": "FC Barcelona (ESP)",
    "Height": 189,
    "Weight": 78
  },
  {
    "Team": "Spain",
    "#": 3,
    "Pos.": "DF",
    "FIFA Popular Name": "PIQUE Gerard",
    "Birth Date": "02.02.1987",
    "Shirt Name": "PIQUÉ",
    "Club": "FC Barcelona (ESP)",
    "Height": 194,
    "Weight": 85
  },
  {
    "Team": "Uruguay",
    "#": 9,
    "Pos.": "FW",
    "FIFA Popular Name": "SUAREZ Luis",
    "Birth Date": "24.01.1987",
    "Shirt Name": "SUAREZ",
    "Club": "FC Barcelona (ESP)",
    "Height": 182,
    "Weight": 85
  },
  {
    "Team": "Colombia",
    "#": 10,
    "Pos.": "MF",
    "FIFA Popular Name": "RODRIGUEZ James",
    "Birth Date": "12.07.1991",
    "Shirt Name": "JAMES",
    "Club": "FC Bayern München (GER)",
    "Height": 180,
    "Weight": 75
  },
  {
    "Team": "France",
    "#": 12,
    "Pos.": "MF",
    "FIFA Popular Name": "TOLISSO Corentin",
    "Birth Date": "03.08.1994",
    "Shirt Name": "TOLISSO",
    "Club": "FC Bayern München (GER)",
    "Height": 180,
    "Weight": 82
  },
  {
    "Team": "Germany",
    "#": 18,
    "Pos.": "DF",
    "FIFA Popular Name": "KIMMICH Joshua",
    "Birth Date": "08.02.1995",
    "Shirt Name": "KIMMICH",
    "Club": "FC Bayern München (GER)",
    "Height": 176,
    "Weight": 72
  },
  {
    "Team": "Germany",
    "#": 19,
    "Pos.": "MF",
    "FIFA Popular Name": "RUDY Sebastian",
    "Birth Date": "28.02.1990",
    "Shirt Name": "RUDY",
    "Club": "FC Bayern München (GER)",
    "Height": 179,
    "Weight": 74
  },
  {
    "Team": "Germany",
    "#": 13,
    "Pos.": "MF",
    "FIFA Popular Name": "MUELLER Thomas",
    "Birth Date": "13.09.1989",
    "Shirt Name": "MÜLLER",
    "Club": "FC Bayern München (GER)",
    "Height": 186,
    "Weight": 75
  },
  {
    "Team": "Germany",
    "#": 15,
    "Pos.": "DF",
    "FIFA Popular Name": "SUELE Niklas",
    "Birth Date": "03.09.1995",
    "Shirt Name": "SÜLE",
    "Club": "FC Bayern München (GER)",
    "Height": 195,
    "Weight": 89
  },
  {
    "Team": "Germany",
    "#": 5,
    "Pos.": "DF",
    "FIFA Popular Name": "HUMMELS Mats",
    "Birth Date": "16.12.1988",
    "Shirt Name": "HUMMELS",
    "Club": "FC Bayern München (GER)",
    "Height": 192,
    "Weight": 90
  },
  {
    "Team": "Germany",
    "#": 17,
    "Pos.": "DF",
    "FIFA Popular Name": "BOATENG Jerome",
    "Birth Date": "03.09.1988",
    "Shirt Name": "BOATENG",
    "Club": "FC Bayern München (GER)",
    "Height": 192,
    "Weight": 90
  },
  {
    "Team": "Germany",
    "#": 1,
    "Pos.": "GK",
    "FIFA Popular Name": "NEUER Manuel",
    "Birth Date": "27.03.1986",
    "Shirt Name": "NEUER",
    "Club": "FC Bayern München (GER)",
    "Height": 193,
    "Weight": 93
  },
  {
    "Team": "Poland",
    "#": 9,
    "Pos.": "FW",
    "FIFA Popular Name": "LEWANDOWSKI Robert",
    "Birth Date": "21.08.1988",
    "Shirt Name": "LEWANDOWSKI",
    "Club": "FC Bayern München (GER)",
    "Height": 185,
    "Weight": 79
  },
  {
    "Team": "Spain",
    "#": 10,
    "Pos.": "MF",
    "FIFA Popular Name": "THIAGO",
    "Birth Date": "11.04.1991",
    "Shirt Name": "THIAGO",
    "Club": "FC Bayern München (GER)",
    "Height": 174,
    "Weight": 70
  },
  {
    "Team": "Argentina",
    "#": 21,
    "Pos.": "FW",
    "FIFA Popular Name": "DYBALA Paulo",
    "Birth Date": "15.11.1993",
    "Shirt Name": "DYBALA",
    "Club": "Juventus FC (ITA)",
    "Height": 177,
    "Weight": 73
  },
  {
    "Team": "Argentina",
    "#": 9,
    "Pos.": "FW",
    "FIFA Popular Name": "HIGUAIN Gonzalo",
    "Birth Date": "10.12.1987",
    "Shirt Name": "HIGUAÍN",
    "Club": "Juventus FC (ITA)",
    "Height": 184,
    "Weight": 75
  },
  {
    "Team": "Brazil",
    "#": 7,
    "Pos.": "FW",
    "FIFA Popular Name": "DOUGLAS COSTA",
    "Birth Date": "14.09.1990",
    "Shirt Name": "D. COSTA",
    "Club": "Juventus FC (ITA)",
    "Height": 182,
    "Weight": 70
  },
  {
    "Team": "Colombia",
    "#": 11,
    "Pos.": "MF",
    "FIFA Popular Name": "CUADRADO Juan",
    "Birth Date": "26.05.1988",
    "Shirt Name": "CUADRADO",
    "Club": "Juventus FC (ITA)",
    "Height": 179,
    "Weight": 72
  },
  {
    "Team": "Croatia",
    "#": 17,
    "Pos.": "FW",
    "FIFA Popular Name": "MANDZUKIC Mario",
    "Birth Date": "21.05.1986",
    "Shirt Name": "MANDŽUKIĆ",
    "Club": "Juventus FC (ITA)",
    "Height": 190,
    "Weight": 85
  },
  {
    "Team": "France",
    "#": 14,
    "Pos.": "MF",
    "FIFA Popular Name": "MATUIDI Blaise",
    "Birth Date": "09.04.1987",
    "Shirt Name": "MATUIDI",
    "Club": "Juventus FC (ITA)",
    "Height": 180,
    "Weight": 74
  },
  {
    "Team": "Germany",
    "#": 6,
    "Pos.": "DF",
    "FIFA Popular Name": "KHEDIRA Sami",
    "Birth Date": "04.04.1987",
    "Shirt Name": "KHEDIRA",
    "Club": "Juventus FC (ITA)",
    "Height": 189,
    "Weight": 81
  },
  {
    "Team": "Morocco",
    "#": 5,
    "Pos.": "DF",
    "FIFA Popular Name": "BENATIA Mehdi",
    "Birth Date": "17.04.1987",
    "Shirt Name": "BENATIA",
    "Club": "Juventus FC (ITA)",
    "Height": 188,
    "Weight": 88
  },
  {
    "Team": "Poland",
    "#": 1,
    "Pos.": "GK",
    "FIFA Popular Name": "SZCZESNY Wojciech",
    "Birth Date": "18.04.1990",
    "Shirt Name": "SZCZESNY",
    "Club": "Juventus FC (ITA)",
    "Height": 195,
    "Weight": 84
  },
  {
    "Team": "Switzerland",
    "#": 2,
    "Pos.": "DF",
    "FIFA Popular Name": "LICHTSTEINER Stephan",
    "Birth Date": "16.01.1984",
    "Shirt Name": "LICHTSTEINER",
    "Club": "Juventus FC (ITA)",
    "Height": 181,
    "Weight": 77
  },
  {
    "Team": "Uruguay",
    "#": 6,
    "Pos.": "MF",
    "FIFA Popular Name": "BENTANCUR Rodrigo",
    "Birth Date": "25.06.1997",
    "Shirt Name": "BENTANCUR",
    "Club": "Juventus FC (ITA)",
    "Height": 187,
    "Weight": 73
  }
 ]